#!/usr/bin/env python3
"""study/11 S5: write iris-engine/start-eye.js — the instant stand-in of every eye in the arrival rotation.

Each stand-in is its case's own globals, collarette and view (ref/cases.json, the case the layer model is measured on),
about 5 KB: the first frame is the procedural engine in that eye's colours and pose, never the seed-42 brown, and
tissue-ui.js then loads that eye's layer model quietly. One eye is chosen per visit and kept for the browser session,
so a reload does not swap the eye under the visitor. An eye joins ACCEPTED only after iori has looked at its review
sheet (study/proof-layers/t7-review-NN.png).

    python3 iris-engine/tools/t7/start_eyes.py
"""
import json, os
ENG = os.path.normpath(os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', '..'))
ACCEPTED = ['25', '26', '35']            # iori, 2026-09-22: 25 and 35 look good; 09 waits for its blue
cases = json.load(open(os.path.join(ENG, 'ref', 'cases.json')))
eyes = {}
for ref in ACCEPTED:
    f = next(k for k in cases if k.startswith(ref + '-')); c = cases[f]
    eyes[ref] = {'file': f, 'seed': c['genome']['seed'], 'globals': c['genome']['globals'], 'coll': c['genome']['coll'], 'view': c['view']}
js = f'''// start-eye.js — the eyes a visitor meets (study/10 §11 S1, study/11 S5). GENERATED by tools/t7/start_eyes.py from
// ref/cases.json — do not edit by hand; regenerate when a case changes or an eye joins the rotation.
// Each is the procedural engine in that eye's OWN colours, collarette and pose (the instant frame); tissue-ui.js then
// loads the eye's layer model in the background. One per visit, kept for the browser session. Not applied when the URL
// carries an eye (#id=, #seed=), with ?start=off (tests, benches), or when a kept session (session.js) comes back.
// ?eye=NN picks one (and keeps it for the session).
window.__irisStartEyes = {json.dumps(eyes, separators=(',', ':'))};
(() => {{
    const E = window.__irisStartEyes, refs = Object.keys(E), q = /[?&]eye=(\\d\\d)\\b/.exec(location.search);
    let ref = q && E[q[1]] ? q[1] : null;
    try {{ if (!ref) {{ const k = sessionStorage.getItem('irisStartEye'); if (E[k]) ref = k; }} }} catch (e) {{}}
    if (!ref) ref = refs[Math.floor(Math.random() * refs.length)];
    try {{ sessionStorage.setItem('irisStartEye', ref); }} catch (e) {{}}
    window.__irisStartEye = Object.assign({{ ref }}, E[ref]);
}})();
'''
open(os.path.join(ENG, 'start-eye.js'), 'w').write(js)
print('start-eye.js:', ', '.join(ACCEPTED), f'· {len(js) // 1024} KB')
