#!/usr/bin/env python3
"""
site.py — build tooling for iori.me / 3die.fr

Commands:
  scan      Detect new HTML pages missing from pages.meta.json (auto-adds with TODO flag)
  heads     Rewrite deterministic SEO <head> blocks (idempotent, marked region)
  sitemap   Generate sitemap-iori.xml / sitemap-3die.xml / sitemap.xml (lastmod from git)
  robots    Generate robots-iori.txt / robots-3die.txt
  manifest  Generate pages.json (auto-feed for hub pages: catalog, web3d)
  check     Validate registry consistency, uniqueness, coverage
  all       Run scan + heads + sitemap + robots + manifest + check

Zero dependencies — Python 3.9+ stdlib only. Safe to run anywhere (local or server).
"""

import json
import os
import re
import subprocess
import sys
from datetime import date
from xml.sax.saxutils import escape as xml_escape

ROOT = os.path.dirname(os.path.abspath(__file__))
REGISTRY_FILE = os.path.join(ROOT, "pages.meta.json")
MANIFEST_FILE = os.path.join(ROOT, "pages.json")

GA_ID_IORI = "G-GKKJ5VX340"
GA_ID_3DIE = "G-ERECDMYSNT"
GOOGLE_VERIFICATION = "O-GQKbbUV2rUhRtOneHoURp-Q-v7lIbcdP6nfdkrlug"

SEO_BEGIN = "<!-- SEO:BEGIN (generated by site.py — do not edit by hand) -->"
SEO_END = "<!-- SEO:END -->"

LANDING_PAGES = {"iori.me": "iori_INDEX.html", "3die.fr": "index.html"}
PRIORITY_DEFAULT = 0.5


# ---------------------------------------------------------------- registry

def load_registry():
    with open(REGISTRY_FILE, encoding="utf-8") as fh:
        return json.load(fh)["pages"]


def save_registry(pages):
    data = {
        "$schema_note": "Registry for site.py — every public HTML page gets an entry. New pages are auto-added with TODO flags by `python3 site.py scan`. domain = canonical home; hidden = excluded from sitemap/hubs + noindex.",
        "pages": dict(sorted(pages.items())),
    }
    with open(REGISTRY_FILE, "w", encoding="utf-8") as fh:
        json.dump(data, fh, indent=2, ensure_ascii=False)
        fh.write("\n")


def html_files_on_disk():
    return sorted(f for f in os.listdir(ROOT) if f.endswith(".html"))


def page_url(domain, slug):
    return f"https://{domain}/{slug}"


# ---------------------------------------------------------------- git lastmod

def git_lastmod(filename):
    """YYYY-MM-DD of last commit touching the file, else file mtime."""
    try:
        out = subprocess.run(
            ["git", "log", "-1", "--format=%cs", "--", filename],
            cwd=ROOT, capture_output=True, text=True, timeout=10,
        ).stdout.strip()
        if out:
            return out
    except Exception:
        pass
    try:
        return date.fromtimestamp(os.path.getmtime(os.path.join(ROOT, filename))).isoformat()
    except OSError:
        return date.today().isoformat()


# ---------------------------------------------------------------- head rewriting

REMOVE_PATTERNS = [
    r"<title>.*?</title>",
    r'<meta\s+name="description"[^>]*>',
    r'<meta\s+name="keywords"[^>]*>',
    r'<meta\s+name="author"[^>]*>',
    r'<meta\s+name="robots"[^>]*>',
    r'<meta\s+property="og:[^"]*"[^>]*>',
    r'<meta\s+name="twitter:[^"]*"[^>]*>',
    r'<link\s+rel="canonical"[^>]*>',
    r'<meta\s+name="google-site-verification"[^>]*>',
    r'<meta\s+name="theme-color"[^>]*>',
    r'<link\s+rel="manifest"[^>]*>',
    r'<link\s+rel="(?:shortcut )?icon"[^>]*>',
    r'<link\s+rel="apple-touch-icon[^"]*"[^>]*>',
    r'<script\s+async\s+src="https://www\.googletagmanager\.com/gtag/js[^"]*"></script>',
    r'<script\s+type="application/ld\+json">.*?</script>',
    # legacy combined GA + canonical-injector inline script
    r'<script>\s*(?:/\*\*? Dynamic SEO[^>]*?\*/\s*)?window\.dataLayer.*?</script>',
    r'<!--\s*Dynamic SEO[^>]*-->',
    r'[ \t]*<!-- SEO:BEGIN.*?SEO:END -->[ \t]*\n?',
]


def strip_old_seo(head_html):
    for pat in REMOVE_PATTERNS:
        head_html = re.sub(pat, "", head_html, flags=re.S | re.I)
    # normalize whitespace-only lines, then collapse 3+ newlines (idempotent)
    head_html = re.sub(r"^[ \t]+$", "", head_html, flags=re.M)
    head_html = re.sub(r"\n{3,}", "\n\n", head_html)
    return head_html


def json_ld_for(slug, meta):
    domain, title, desc = meta["domain"], meta["title"], meta["description"]
    url = page_url(domain, slug)
    blocks = [
        {
            "@context": "https://schema.org",
            "@type": "Organization",
            "name": "3DIE",
            "url": "https://3die.fr/",
            "sameAs": ["https://iori.me/"],
        }
    ]
    ptype = meta.get("type", "experiment")
    if ptype == "game":
        blocks.append({
            "@context": "https://schema.org",
            "@type": "VideoGame",
            "name": title, "description": desc, "url": url,
            "gamePlatform": "Web Browser", "applicationCategory": "Game",
            "author": {"@type": "Organization", "name": "3DIE"},
        })
    elif ptype == "artist":
        blocks.append({
            "@context": "https://schema.org",
            "@type": "Person",
            "name": title.split("—")[0].strip(), "url": url,
            "memberOf": {"@type": "Organization", "name": "3DIE"},
        })
    elif ptype == "experiment":
        blocks.append({
            "@context": "https://schema.org",
            "@type": "CreativeWork",
            "name": title, "description": desc, "url": url,
            "author": {"@type": "Person", "name": "iori", "url": "https://iori.me/"},
        })
    return blocks


def build_seo_block(slug, meta):
    domain, title, desc = meta["domain"], meta["title"], meta["description"]
    url = page_url(domain, slug)
    hidden = bool(meta.get("hidden"))
    robots = "noindex, nofollow" if hidden else "index, follow, max-image-preview:large"
    og_image = meta.get("og_image")
    og_image_url = f"https://{domain}/{og_image}" if og_image else None

    lines = [
        SEO_BEGIN,
        f"    <title>{title}</title>",
        f'    <meta name="description" content="{desc}">',
        f'    <meta name="robots" content="{robots}">',
        f'    <link rel="canonical" href="{url}">',
        "",
        f'    <meta property="og:type" content="website">',
        f'    <meta property="og:title" content="{title}">',
        f'    <meta property="og:description" content="{desc}">',
        f'    <meta property="og:url" content="{url}">',
        f'    <meta property="og:site_name" content="{"3DIE" if domain == "3die.fr" else "iori"}">',
        f'    <meta property="og:locale" content="en_US">',
    ]
    if og_image_url:
        lines.append(f'    <meta property="og:image" content="{og_image_url}">')
        lines.append(f'    <meta name="twitter:card" content="summary_large_image">')
        lines.append(f'    <meta name="twitter:image" content="{og_image_url}">')
    else:
        lines.append('    <meta name="twitter:card" content="summary">')
    lines += [
        f'    <meta name="twitter:title" content="{title}">',
        f'    <meta name="twitter:description" content="{desc}">',
        "",
        '    <meta name="theme-color" content="#000000">',
        '    <link rel="manifest" href="manifest.json">',
        '    <link rel="icon" type="image/png" sizes="32x32" href="icon/ios/32.png">',
        '    <link rel="icon" type="image/png" sizes="16x16" href="icon/ios/16.png">',
        '    <link rel="apple-touch-icon" href="icon/ios/180.png">',
        "",
        f'    <meta name="google-site-verification" content="{GOOGLE_VERIFICATION}" />',
        "",
        "    <!-- Google Analytics (per-domain property chosen by hostname) -->",
        f'    <script async src="https://www.googletagmanager.com/gtag/js?id={GA_ID_IORI}"></script>',
        f'    <script async src="https://www.googletagmanager.com/gtag/js?id={GA_ID_3DIE}"></script>',
        "    <script>",
        "      window.dataLayer = window.dataLayer || [];",
        "      function gtag(){dataLayer.push(arguments);}",
        "      gtag('js', new Date());",
        "      if (window.location.hostname.includes('3die.fr')) {",
        f"          gtag('config', '{GA_ID_3DIE}');",
        "      } else {",
        f"          gtag('config', '{GA_ID_IORI}');",
        "      }",
        "    </script>",
        "",
    ]
    for block in json_ld_for(slug, meta):
        lines.append('    <script type="application/ld+json">')
        lines.append("      " + json.dumps(block, ensure_ascii=False))
        lines.append("    </script>")
    lines.append("    " + SEO_END)
    return "\n".join(lines)


def ensure_viewport(head_html):
    """Normalize viewport for mobile readiness; keep pages that have none."""
    if 'name="viewport"' in head_html:
        head_html = re.sub(
            r'<meta\s+name="viewport"[^>]*>',
            '<meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover">',
            head_html, flags=re.I,
        )
    return head_html


def rewrite_head(path, slug, meta):
    with open(path, encoding="utf-8", errors="ignore") as fh:
        content = fh.read()

    head_match = re.search(r"(<head[^>]*>)(.*?)(</head>)", content, flags=re.S | re.I)
    if not head_match:
        return False, "no <head> found"

    head_open, head_body, head_close = head_match.groups()
    body = strip_old_seo(head_body)
    body = ensure_viewport(body)

    has_charset = re.search(r'<meta\s+charset', body, flags=re.I)
    block = build_seo_block(slug, meta)

    if has_charset:
        # insert generated block right after charset meta (charset stays first)
        body = re.sub(
            r'(<meta\s+charset[^>]*>)',
            r"\1\n" + block,
            body, count=1, flags=re.I,
        )
    else:
        body = '\n    <meta charset="utf-8">\n' + block + "\n" + body.lstrip()

    new_content = content[: head_match.start()] + head_open + body + head_close + content[head_match.end():]
    with open(path, "w", encoding="utf-8") as fh:
        fh.write(new_content)
    return True, "ok"


# ---------------------------------------------------------------- commands

def cmd_scan():
    pages = load_registry()
    on_disk = html_files_on_disk()
    added, missing_files = [], []
    for slug in on_disk:
        if slug not in pages:
            pages[slug] = {
                "title": slug.replace(".html", "").replace("-", " ").title() + " — TODO",
                "description": "TODO: write a unique description for this page.",
                "category": "TODO", "domain": "iori.me", "type": "experiment",
                "priority": PRIORITY_DEFAULT, "todo": True,
            }
            added.append(slug)
    for slug in list(pages):
        if slug not in on_disk:
            missing_files.append(slug)
    if added:
        save_registry(pages)
    print(f"[scan] {len(on_disk)} html files, {len(pages)} registry entries")
    for s in added:
        print(f"  + auto-added (TODO): {s}")
    for s in missing_files:
        print(f"  ! registry entry without file: {s}")
    return not missing_files


def cmd_heads():
    pages = load_registry()
    ok, failed = 0, []
    for slug, meta in pages.items():
        path = os.path.join(ROOT, slug)
        if not os.path.exists(path):
            continue
        success, msg = rewrite_head(path, slug, meta)
        if success:
            ok += 1
        else:
            failed.append((slug, msg))
    print(f"[heads] rewrote {ok} pages")
    for slug, msg in failed:
        print(f"  ! {slug}: {msg}")
    return not failed


def cmd_sitemap():
    pages = load_registry()
    by_domain = {}
    for slug, meta in pages.items():
        if meta.get("hidden"):
            continue
        by_domain.setdefault(meta["domain"], []).append((slug, meta))

    for domain, entries in by_domain.items():
        landing = LANDING_PAGES.get(domain)
        urls = []
        for slug, meta in sorted(entries):
            if slug == landing:
                loc = f"https://{domain}/"
            else:
                loc = page_url(domain, slug)
            urls.append((loc, git_lastmod(slug), meta.get("priority", PRIORITY_DEFAULT)))

        xml = ['<?xml version="1.0" encoding="UTF-8"?>',
               '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">']
        # landing page first
        urls.sort(key=lambda u: (u[0] != f"https://{domain}/", u[0]))
        for loc, lastmod, priority in urls:
            xml.append("  <url>")
            xml.append(f"    <loc>{xml_escape(loc)}</loc>")
            xml.append(f"    <lastmod>{lastmod}</lastmod>")
            xml.append(f"    <priority>{priority:.1f}</priority>")
            xml.append("  </url>")
        xml.append("</urlset>")

        suffix = "iori" if domain == "iori.me" else "3die"
        out = os.path.join(ROOT, f"sitemap-{suffix}.xml")
        with open(out, "w", encoding="utf-8") as fh:
            fh.write("\n".join(xml) + "\n")
        print(f"[sitemap] {out} ({len(urls)} urls)")

    # legacy combined sitemap.xml = iori list (Caddy rewrites per domain anyway)
    iori = os.path.join(ROOT, "sitemap-iori.xml")
    if os.path.exists(iori):
        with open(iori, encoding="utf-8") as fh:
            data = fh.read()
        with open(os.path.join(ROOT, "sitemap.xml"), "w", encoding="utf-8") as fh:
            fh.write(data)
    return True


def cmd_robots():
    pages = load_registry()
    hidden = sorted(s for s, m in pages.items() if m.get("hidden"))
    for domain, suffix in (("iori.me", "iori"), ("3die.fr", "3die")):
        lines = [
            "User-agent: *",
            "Allow: /",
            "Disallow: /api/",
        ]
        for slug in hidden:
            lines.append(f"Disallow: /{slug}")
        lines += [
            "",
            f"Sitemap: https://{domain}/sitemap-{suffix}.xml",
        ]
        out = os.path.join(ROOT, f"robots-{suffix}.txt")
        with open(out, "w", encoding="utf-8") as fh:
            fh.write("\n".join(lines) + "\n")
        print(f"[robots] {out}")
    return True


def cmd_manifest():
    pages = load_registry()
    entries = []
    for slug, meta in sorted(pages.items()):
        if meta.get("hidden"):
            continue
        entries.append({
            "slug": slug,
            "title": meta["title"],
            "description": meta["description"],
            "category": meta.get("category", "misc"),
            "type": meta.get("type", "experiment"),
            "domain": meta["domain"],
            "url": page_url(meta["domain"], slug),
            "og_image": meta.get("og_image"),
            "lastmod": git_lastmod(slug),
        })
    data = {"generated": date.today().isoformat(), "pages": entries}
    with open(MANIFEST_FILE, "w", encoding="utf-8") as fh:
        json.dump(data, fh, indent=2, ensure_ascii=False)
        fh.write("\n")
    print(f"[manifest] {MANIFEST_FILE} ({len(entries)} pages)")
    return True


def cmd_caddy():
    """Generate per-domain 301 redirect maps (imported by the Caddyfile).

    Every page has exactly one canonical home domain. On the other domain,
    requests 301-redirect to the canonical URL — eliminating duplicate content.
    """
    pages = load_registry()
    domains = ("iori.me", "3die.fr")
    for domain in domains:
        foreign = []
        for slug, meta in sorted(pages.items()):
            if meta.get("hidden") or meta["domain"] == domain:
                continue
            home = meta["domain"]
            landing = LANDING_PAGES.get(home)
            target = f"https://{home}/" if slug == landing else page_url(home, slug)
            foreign.append((slug, target))
        lines = [
            f"# generated by site.py — cross-domain 301s for {domain}",
            f"# (pages whose canonical home is the other domain)",
        ]
        for slug, target in foreign:
            lines.append(f"redir /{slug} {target} permanent")
        suffix = "iori" if domain == "iori.me" else "3die"
        out = os.path.join(ROOT, f"redirects-{suffix}.caddy")
        with open(out, "w", encoding="utf-8") as fh:
            fh.write("\n".join(lines) + "\n")
        print(f"[caddy] {out} ({len(foreign)} redirects)")
    return True


def cmd_check():
    pages = load_registry()
    on_disk = set(html_files_on_disk())
    problems, warnings = [], []

    titles, descs = {}, {}
    for slug, meta in pages.items():
        if slug not in on_disk:
            problems.append(f"registry entry without file: {slug}")
        if meta.get("todo"):
            warnings.append(f"TODO metadata: {slug}")
        t, d = meta.get("title", ""), meta.get("description", "")
        if t in titles:
            problems.append(f"duplicate title: {slug} == {titles[t]} ({t!r})")
        titles[t] = slug
        if d in descs:
            problems.append(f"duplicate description: {slug} == {descs[d]}")
        descs[d] = slug
        if len(d) < 50:
            warnings.append(f"short description ({len(d)} chars): {slug}")
        if len(d) > 170:
            warnings.append(f"long description ({len(d)} chars): {slug}")
        if meta.get("domain") not in ("iori.me", "3die.fr"):
            problems.append(f"invalid domain: {slug} -> {meta.get('domain')}")
    for slug in sorted(on_disk - set(pages)):
        problems.append(f"file without registry entry: {slug}")

    print(f"[check] {len(pages)} pages checked")
    for w in warnings:
        print(f"  warn: {w}")
    for p in problems:
        print(f"  FAIL: {p}")
    if not problems:
        print("  all checks passed")
    return not problems


COMMANDS = {
    "scan": cmd_scan, "heads": cmd_heads, "sitemap": cmd_sitemap,
    "robots": cmd_robots, "manifest": cmd_manifest, "check": cmd_check,
    "caddy": cmd_caddy,
}


def main():
    args = sys.argv[1:]
    if not args or args[0] in ("-h", "--help"):
        print(__doc__)
        return 0
    if args[0] == "all":
        ok = True
        for name in ("scan", "heads", "sitemap", "robots", "manifest", "caddy", "check"):
            ok = COMMANDS[name]() and ok
        return 0 if ok else 1
    if args[0] not in COMMANDS:
        print(f"unknown command: {args[0]}")
        print(__doc__)
        return 1
    return 0 if COMMANDS[args[0]]() else 1


if __name__ == "__main__":
    sys.exit(main())
